kind = "DojoContract"
class_hash = "0x5bd4c7cb0548f8b5c0d2186ab1c88f48ecaaaa28cf0046f77b58909bb2d6d97"
original_class_hash = "0x5bd4c7cb0548f8b5c0d2186ab1c88f48ecaaaa28cf0046f77b58909bb2d6d97"
base_class_hash = "0x0"
abi = "manifests/prod/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_starter::systems::actions::actions"
