kind = "DojoContract"
class_hash = "0x69a578ad8c3dbd59abd2706cdac8199f1297224c02303b1bf0995758a6da7c2"
original_class_hash = "0x69a578ad8c3dbd59abd2706cdac8199f1297224c02303b1bf0995758a6da7c2"
base_class_hash = "0x0"
abi = "manifests/prod/base/abis/contracts/dojo_starter-actions-7a1c7102.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_starter-actions"
manifest_name = "dojo_starter-actions-7a1c7102"
