[world]
kind = "WorldContract"
class_hash = "0x32fb65ebfe6d91bb4b7ba0640650722c43ca0c917f5fc0f649ee2ecf720cde"
original_class_hash = "0x32fb65ebfe6d91bb4b7ba0640650722c43ca0c917f5fc0f649ee2ecf720cde"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x70835f8344647b1e573fe7aeccbf044230089eb19624d3c7dea4080f5dcb025"
transaction_hash = "0x51a2a73afb296548a8452242d4075fb51903b78b884ac97dc9d5ea573d0816b"
block_number = 14
seed = "dojo_starter"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x5f4c155f43bdc72bcedeb4cc20cac9fe62102a2d86f13b0bd4473066824b69"
class_hash = "0x5c94d6b13db61b18ee45e2e0a6bbf0c8123dd7a43c20a6edccb99ff5958001d"
original_class_hash = "0x5c94d6b13db61b18ee45e2e0a6bbf0c8123dd7a43c20a6edccb99ff5958001d"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_starter-actions-7a1c7102.json"
reads = []
writes = [
    "dojo_starter-Tile",
    "dojo_starter-Player",
]
computed = []
init_calldata = []
tag = "dojo_starter-actions"
manifest_name = "dojo_starter-actions-7a1c7102"

[[models]]
kind = "DojoModel"
class_hash = "0x65b235745c25d85b48b16e55e79832c40638e85895a5895fa521398d39d96b6"
original_class_hash = "0x65b235745c25d85b48b16e55e79832c40638e85895a5895fa521398d39d96b6"
abi = "manifests/dev/deployment/abis/models/dojo_starter-Player-1cccb05d.json"
tag = "dojo_starter-Player"
manifest_name = "dojo_starter-Player-1cccb05d"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "last_action"
type = "u64"
key = false

[[models.members]]
name = "points"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xce7fcf02e142e917f160737b7988a25da6594fffaa193fb4f61a29bee1f52d"
original_class_hash = "0xce7fcf02e142e917f160737b7988a25da6594fffaa193fb4f61a29bee1f52d"
abi = "manifests/dev/deployment/abis/models/dojo_starter-Tile-269db396.json"
tag = "dojo_starter-Tile"
manifest_name = "dojo_starter-Tile-269db396"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "color"
type = "felt252"
key = false

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false
