[world]
kind = "WorldContract"
class_hash = "0x32fb65ebfe6d91bb4b7ba0640650722c43ca0c917f5fc0f649ee2ecf720cde"
original_class_hash = "0x32fb65ebfe6d91bb4b7ba0640650722c43ca0c917f5fc0f649ee2ecf720cde"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x177292c9085a51b0a5df818f11cbbb6cd18bf6e3c372219746bc8f92e8c83b5"
transaction_hash = "0x78990fc2e4abd71716cdc313abb1945c8469329e9b4aaf75aa6f665c2cbaa86"
block_number = 16
seed = "rps_game"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x7908aacf69a8a47b414b5f82e36b1ce2a50e295ad9329b75780b30df4c58fc3"
class_hash = "0x4fc6987c5da77abf7545be7b0420f5da817fcad2cfcd598c6d4cc49d0b7807f"
original_class_hash = "0x4fc6987c5da77abf7545be7b0420f5da817fcad2cfcd598c6d4cc49d0b7807f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/rps_game-actions-3af54743.json"
reads = []
writes = [
    "rps_game-Tile",
    "rps_game-Player",
]
computed = []
init_calldata = []
tag = "rps_game-actions"
manifest_name = "rps_game-actions-3af54743"

[[models]]
kind = "DojoModel"
class_hash = "0x4e2c649045e6a7d138d16b084c6e7bd07bd45b9eba200f0eaf4713254fb65bd"
original_class_hash = "0x4e2c649045e6a7d138d16b084c6e7bd07bd45b9eba200f0eaf4713254fb65bd"
abi = "manifests/dev/deployment/abis/models/rps_game-Player-407f5d6b.json"
tag = "rps_game-Player"
manifest_name = "rps_game-Player-407f5d6b"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "last_action"
type = "u64"
key = false

[[models.members]]
name = "points"
type = "u64"
key = false

[[models.members]]
name = "faction"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x269b4d380152329b48a7b367b7331f95c28a4cf1582a07c079490823e48e05"
original_class_hash = "0x269b4d380152329b48a7b367b7331f95c28a4cf1582a07c079490823e48e05"
abi = "manifests/dev/deployment/abis/models/rps_game-Tile-786a5c71.json"
tag = "rps_game-Tile"
manifest_name = "rps_game-Tile-786a5c71"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "state"
type = "felt252"
key = false

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false
