kind = "DojoModel"
class_hash = "0x269b4d380152329b48a7b367b7331f95c28a4cf1582a07c079490823e48e05"
original_class_hash = "0x269b4d380152329b48a7b367b7331f95c28a4cf1582a07c079490823e48e05"
abi = "manifests/dev/base/abis/models/rps_game-Tile-786a5c71.json"
tag = "rps_game-Tile"
manifest_name = "rps_game-Tile-786a5c71"

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "state"
type = "felt252"
key = false

[[members]]
name = "owner"
type = "ContractAddress"
key = false
