[world]
kind = "WorldContract"
class_hash = "0x32fb65ebfe6d91bb4b7ba0640650722c43ca0c917f5fc0f649ee2ecf720cde"
original_class_hash = "0x32fb65ebfe6d91bb4b7ba0640650722c43ca0c917f5fc0f649ee2ecf720cde"
abi = "manifests/prod/deployment/abis/dojo-world.json"
address = "0x177292c9085a51b0a5df818f11cbbb6cd18bf6e3c372219746bc8f92e8c83b5"
transaction_hash = "0x4053d183f5fbd7d4ab72ec8dcbabf93f1e1d5b3a1e53136f3279b672ba02c05"
block_number = 3597
seed = "rps_game"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "prod"
rpc_url = "https://api.cartridge.gg/x/color-4/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/prod/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x7908aacf69a8a47b414b5f82e36b1ce2a50e295ad9329b75780b30df4c58fc3"
class_hash = "0x13e68b585d4575d453832903ab0ec67047beea1ef25440044068d40f97a19ed"
original_class_hash = "0x13e68b585d4575d453832903ab0ec67047beea1ef25440044068d40f97a19ed"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/prod/deployment/abis/contracts/rps_game-actions-3af54743.json"
reads = []
writes = [
    "rps_game-Tile",
    "rps_game-Player",
]
computed = []
init_calldata = []
tag = "rps_game-actions"
manifest_name = "rps_game-actions-3af54743"

[[models]]
kind = "DojoModel"
class_hash = "0x5835ea97471041a0da70e3838b811bfbecf0588a31528ef06529dad0419b198"
original_class_hash = "0x5835ea97471041a0da70e3838b811bfbecf0588a31528ef06529dad0419b198"
abi = "manifests/prod/deployment/abis/models/rps_game-Player-407f5d6b.json"
tag = "rps_game-Player"
manifest_name = "rps_game-Player-407f5d6b"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "last_action"
type = "u64"
key = false

[[models.members]]
name = "points"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x36278a23f6469e4479888959ff373c85284d6ee8d4ac087c5d4eeff668ed87b"
original_class_hash = "0x36278a23f6469e4479888959ff373c85284d6ee8d4ac087c5d4eeff668ed87b"
abi = "manifests/prod/deployment/abis/models/rps_game-Tile-786a5c71.json"
tag = "rps_game-Tile"
manifest_name = "rps_game-Tile-786a5c71"

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "color"
type = "felt252"
key = false

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false
