kind = "DojoContract"
class_hash = "0x4fc6987c5da77abf7545be7b0420f5da817fcad2cfcd598c6d4cc49d0b7807f"
original_class_hash = "0x4fc6987c5da77abf7545be7b0420f5da817fcad2cfcd598c6d4cc49d0b7807f"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rps_game-actions-3af54743.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "rps_game-actions"
manifest_name = "rps_game-actions-3af54743"
